from __future__ import annotations

from models import (
    AnimationConfig,
    BenefitItem,
    CapacityBarGeometry,
    CircuitSymbolGeometry,
    ComparisonPanelGeometry,
    ElectricalSymbols,
    EquivalentCircuitGeometry,
    NumericalParameters,
    RenderSettings,
    SceneLayout,
    StyleConfig,
    TextConfig,
    TimingConfig,
    TransmissionLineGeometry,
)


CONFIG = AnimationConfig(
    render=RenderSettings(
        manim_executable=r"C:\tools\Manim\Scripts\manim.exe",
        scene_file="banco_capacitor_serie.py",
        scene_name="SeriesCapacitorScene",
        resolution=(426, 240),
        fps=15,
        preview=False,
    ),
    style=StyleConfig(
        frame_width=16.0,
        frame_height=9.0,
        background_color="#0B1020",
        line_color="#8FD3FF",
        tower_color="#C9D6E3",
        capacitor_color="#FFB000",
        power_color="#32E875",
        warning_color="#FF5C5C",
        text_color="#F4F7FB",
        muted_text_color="#9FB3C8",
        panel_fill_color="#111A2E",
        reactance_color="#47A8FF",
        reactance_box_fill_color="#102A44",
    ),
    text=TextConfig(
        source_label="Fonte",
        load_label="Carga",
        capacity_label="Capacidade",
        opening_title="Banco de Capacitor S\u00e9rie",
        opening_subtitle="Como ele aumenta a capacidade de transmiss\u00e3o?",
        long_line_section="1. O problema da linha longa",
        long_line_statement="Linhas longas possuem alta reat\u00e2ncia indutiva",
        long_line_limit_label="limite",
        long_line_x_suffix="maior  \u2192  menor pot\u00eancia transfer\u00edvel",
        uncompensated_section="2. Circuito equivalente sem compensa\u00e7\u00e3o",
        uncompensated_title="Sem compensa\u00e7\u00e3o s\u00e9rie",
        install_section="3. Inser\u00e7\u00e3o do banco de capacitor s\u00e9rie",
        install_title="Instala\u00e7\u00e3o em s\u00e9rie no meio da linha",
        capacitor_bank_title="Banco de Capacitor S\u00e9rie",
        opposite_reactance_text="efeito oposto \u00e0 reat\u00e2ncia indutiva",
        reactance_section="4. Compensa\u00e7\u00e3o da reat\u00e2ncia",
        reactance_before_title="Antes",
        reactance_after_title="Depois",
        reactance_note="A reat\u00e2ncia equivalente da linha diminui",
        comparison_before_title="Antes",
        comparison_after_title="Depois",
        comparison_before_reactance_suffix="alto",
        comparison_after_reactance_suffix="menor",
        comparison_before_power="Pot\u00eancia limitada",
        comparison_before_stability="Menor margem de estabilidade",
        comparison_after_power="Maior transfer\u00eancia de pot\u00eancia",
        comparison_after_stability="Melhor estabilidade",
        power_section="5. Aumento da pot\u00eancia transfer\u00edvel",
        benefits_section="6. Benef\u00edcios pr\u00e1ticos",
        benefits_title="Por que usar compensa\u00e7\u00e3o s\u00e9rie?",
        benefits=(
            BenefitItem("\u2191", "Aumenta a capacidade de transmiss\u00e3o", "power"),
            BenefitItem("V", "Reduz queda de tens\u00e3o", "line"),
            BenefitItem("\u03b4", "Melhora a estabilidade do sistema", "capacitor"),
            BenefitItem("+", "Evita ou adia a constru\u00e7\u00e3o de novas linhas", "muted"),
        ),
        closing_text=(
            "O banco de capacitor s\u00e9rie compensa parte da reat\u00e2ncia da linha\n"
            "e permite transmitir mais pot\u00eancia com maior estabilidade."
        ),
    ),
    symbols=ElectricalSymbols(
        source_voltage="V_s",
        receiver_voltage="V_r",
        inductive_reactance="X_L",
        capacitive_reactance="X_C",
        equivalent_reactance="X_{eq}",
        maximum_power=r"P_{\rm{max}}",
    ),
    numerical=NumericalParameters(
        uncompensated_capacity_fraction=0.43,
        before_capacity_fraction=0.42,
        after_capacity_fraction=0.82,
    ),
    line=TransmissionLineGeometry(
        support_x_coordinates=(-6.0, -4.0, 0.0, 4.0, 6.0),
        tower_x_coordinates=(-4.0, 0.0, 4.0),
        tower_y=-1.2,
        tower_scale=0.9,
        source_x=-6.75,
        load_x=6.75,
        terminal_y=-1.15,
        terminal_scale=0.9,
        phase_y_coordinates=(-0.50, -0.83, -1.16),
        phase_sags=(0.20, 0.24, 0.28),
        phase_stroke_widths=(4.0, 3.0, 3.0),
        catenary_tension=1.45,
        capacitor_y=-0.55,
        capacitor_scale=0.85,
    ),
    symbols_geometry=CircuitSymbolGeometry(
        capacitor_lead_half_width=0.9,
        capacitor_plate_half_gap=0.11,
        capacitor_plate_half_height=0.42,
        capacitor_lead_stroke_width=4.0,
        capacitor_plate_stroke_width=6.0,
        inductor_terminal_half_width=1.4,
        inductor_loop_count=5,
        inductor_loop_pitch=0.22,
        inductor_loop_radius_x=0.18,
        inductor_loop_radius_y=0.32,
    ),
    equivalent_circuit=EquivalentCircuitGeometry(
        source_x=-5.2,
        receiver_x=5.2,
        terminal_radius=0.42,
        inductor_x_with_capacitor=-1.75,
        inductor_x_without_capacitor=0.0,
        inductor_scale=0.9,
        capacitor_x=1.45,
        capacitor_scale=0.65,
        capacitor_label_buff=0.15,
    ),
    capacity_bar=CapacityBarGeometry(
        height=0.34,
        corner_radius=0.08,
        stroke_width=2.0,
        minimum_fill_width=0.05,
        fill_opacity=0.75,
        label_font_size=24,
        label_buff=0.14,
    ),
    comparison_panel=ComparisonPanelGeometry(
        box_width=5.8,
        box_height=3.7,
        corner_radius=0.18,
        center_offset_x=3.25,
        title_font_size=32,
        item_font_size=25,
        item_vertical_buff=0.28,
        title_top_buff=0.25,
        item_center_shift_y=0.25,
        capacity_bar_width=3.6,
        capacity_bar_scale=0.8,
        capacity_bar_bottom_buff=0.35,
    ),
    layout=SceneLayout(
        manim_units_per_centimeter=0.55,
        section_label_font_size=26,
        section_label_corner_buff=0.35,
        opening_line_scale=0.98,
        opening_line_shift_y=0.55,
        opening_arrow_start_x=-5.4,
        opening_arrow_end_x=5.4,
        opening_arrow_y=0.06,
        opening_arrow_count=5,
        opening_arrow_width=5.0,
        long_line_scale=0.94,
        long_line_shift_y=0.45,
        long_line_statement_top_buff=0.76,
        long_line_statement_down_shift=0.55,
        long_line_xl_block_y=1.05,
        long_line_xl_block_width=1.45,
        long_line_xl_block_height=0.75,
        long_line_xl_block_corner_radius=0.12,
        long_line_warning_x=2.2,
        long_line_warning_y=0.28,
        long_line_warning_arrow_start_x=-2.6,
        long_line_warning_arrow_end_x=1.75,
        long_line_formula_bottom_buff=0.38,
        long_line_formula_up_shift=0.55,
        long_line_note_buff=0.20,
        uncompensated_title_top_buff=0.7,
        uncompensated_title_down_shift=0.55,
        uncompensated_circuit_shift_y=0.15,
        uncompensated_equation_buff=0.55,
        uncompensated_bar_buff=0.55,
        install_title_top_buff=0.7,
        install_title_down_shift=0.55,
        install_line_scale=0.92,
        install_line_shift_y=-0.45,
        install_capacitor_scale_multiplier=0.95,
        install_capacitor_title_buff=0.55,
        install_xc_label_buff=0.22,
        install_xl_position=(-2.4, 0.35),
        install_opposite_text_buff=0.22,
        install_text_group_shift_y=1.65,
        install_symbol_group_shift_y=0.55,
        reactance_equation_top_buff=0.95,
        reactance_equation_down_shift=0.55,
        reactance_label_y=0.75,
        reactance_before_x=-3.3,
        reactance_after_x=3.3,
        reactance_before_bar_width=4.5,
        reactance_after_bar_width=2.65,
        reactance_removed_width=1.85,
        reactance_bar_height=0.55,
        reactance_arrow_gap=0.4,
        reactance_xc_label_buff=0.18,
        reactance_note_bottom_buff=0.75,
        power_formula_top_buff=0.65,
        power_formula_down_shift=0.55,
        power_line_scale=0.9,
        power_line_shift_y=-0.15,
        power_capacitor_up_shift=1.1,
        power_weak_arrow_start_x=-5.05,
        power_weak_arrow_end_x=5.05,
        power_strong_arrow_start_x=-5.4,
        power_strong_arrow_end_x=5.4,
        power_arrow_y=-0.85,
        power_weak_arrow_count=4,
        power_strong_arrow_count=6,
        power_weak_arrow_width=4.0,
        power_strong_arrow_width=7.0,
        power_comparison_scale=0.83,
        power_comparison_bottom_buff=0.25,
        power_final_line_scale=0.75,
        power_final_line_top_buff=1.45,
        power_final_arrow_margin=0.35,
        power_final_formula_y=-0.2,
        benefits_title_top_buff=0.65,
        benefits_title_down_shift=0.55,
        benefits_rows_center_y=-0.15,
        benefits_row_vertical_buff=0.42,
        benefits_row_horizontal_buff=0.35,
        benefits_icon_radius=0.34,
        benefits_icon_font_size=30,
        benefits_text_font_size=31,
        closing_line_scale=0.9,
        closing_line_shift_y=-0.45,
        closing_capacitor_up_shift=1.1,
        closing_text_top_buff=0.75,
        closing_arrow_start_x=-4.8,
        closing_arrow_end_x=4.8,
        closing_arrow_y=-1.0,
        closing_arrow_count=6,
        closing_arrow_width=6.0,
        closing_formula_bottom_buff=0.55,
        closing_formula_horizontal_buff=0.35,
        closing_group_shift_y=1.1,
    ),
    timing=TimingConfig(
        very_fast=0.35,
        fast=1.0,
        medium=1.4,
        slow=2.0,
        very_slow=2.5,
        standard_pause=4.0,
        short_pause=3.0,
        fade_out=1.0,
    ),
)
